feat: add option to specify source and target dirs
This feature enables to copy dot files from or to directories other than
the home directory.

diff --git a/dtm b/dtm
--- a/dtm
+++ b/dtm
@@ -16,23 +16,27 @@ COMMANDS
 	-a, add PATH
 		Start tracking one or more files.
 
+	-e, edit
+		Edit the list of files being tracked manually.
+
 	-r, rm PATH FLAGS
 		Stop tracking the given files. If the flag '--all' is present, remove all files from the track list.
 
 	-l, list, ls
-		List which files are being tracked
+		List files  being tracked
 
 	-L, ln, link DIR FLAGS
-		Create links of all files being tracked to DIR.If the flag '--symbolic' is present, then it will create symbolic links. Otherwise, it will create hard links
+		Create links of tracked files from \$HOME to DIR. If flag '--symbolic' is present, then it will create symbolic links. Otherwise, it will create hard links
 
 	-c, cp, copy DIR
-		Copy all files being tracked to the specified directory.
+		Copy all files being trackedi from \$HOME to DIR.
 
-	-s, sync DIR
-		Copy (or create links from) all files in DIR whose relative path to DIR is in the list of tracked files. Syntax is the same as for command 'link'
+	-s, sync DIR FLAGS
+		Sync dot files from DIR to the HOME directory. If flag '--copy' is present, the files will be copied. If flag '--symbolic' is present, it will create symbolic links. Otherwise, it will create hard links.
 
-	-e, edit
-		Edit the list of files being tracked manually.
+	-S, sync-dirs TARGET DEST FLAGS
+		Sync dot files from TARGET to DEST. Syntax is the same as for the command sync. 
+		
 
 EXAMPLES
 	Add single file to track list
@@ -116,11 +120,12 @@ function trackFiles() {
 		filename=$1
 		shift
 		if ! [ -f "$filename" ]; then
-			echo "ERROR: file \"$filename\" does not exist. Skipping it"
+			echo "file \"$filename\" does not exist. Skipping it"
 			continue
 		fi
 		getPathRelativeToHome $filename >> ${DTM_TRACKED_FILES_LIST}
 	done
+
 	# remove duplicated files
 	LC_ALL=C sort -i $DTM_TRACKED_FILES_LIST | uniq > $DTM_TRACKED_FILES_LIST.tmp
 	mv $DTM_TRACKED_FILES_LIST.tmp $DTM_TRACKED_FILES_LIST
@@ -169,73 +174,55 @@ function untrackFiles() {
 	rm $tmpfile
 }
 
-function createLinks() {
-	destdir=$1
-	[[ -z $destdir ]] && destdir=${DTM_GIT_DIR}
-	[[ -z $destdir ]] && echo 'ERROR: destination directory not specified.' && exit 1
-	[[ ! -d "$destdir" ]] && echo 'ERROR: invalid directory.' && exit 1
-
-	# whether to create symbolic links
-	[[ "$2" == "--symbolic" ]] && symbolic=1
-
-	# do not create links. Instead, copy the file
-	[[ "$2" == "--copy" ]] && copy=1
-
-	# create 
-
-	while read file; do
-		fullpath=$HOME/$file
-
-		if [[ ! -f $fullpath ]]; then
-			echo "File $fullpath does not exist. Skipping it"
-			continue
-		fi
-
-		dir=${file%/*}
-		[[ "$dir" == "$file" ]] && dir=
-
-		mkdir -p "$destdir/$dir"
-		if [[ -n $symbolic ]]; then
-			ln -s "$fullpath" "$destdir/$dir"
-		elif [[ -n $copy ]]; then
-			cp "$fullpath" "$destdir/$dir"
-		else
-			ln "$fullpath" "$destdir/$dir"
-		fi
-
-	done < $DTM_TRACKED_FILES_LIST
+function throwError() {
+	echo "ERROR: $@"
+	exit 1
 }
 
-function syncFrom() {
-	destdir=$1
-	[[ -z $destdir ]] && destdir=${DTM_GIT_DIR}
-	[[ -z $destdir ]] && echo 'ERROR: destination directory not specified.' && exit 1
-	[[ ! -d "$destdir" ]] && echo 'ERROR: invalid directory.' && exit 1
+function syncDotFiles() {
+	source_dir=$1
+	target_dir=$2
+	[[ -z $source_dir ]] && throwError 'source directory not specified'
+	[[ -z $target_dir ]] && throwError 'target directory not specified'
+	[[ ! -d "$source_dir" ]] && throwError 'invalid source directory'
+	[[ ! -d "$target_dir" ]] && throwError 'invalid target directory '
 
-	# whether to create symbolic links
-	[[ "$2" == "--symbolic" ]] && symbolic=1
-
-	# do not create links. Instead, copy the file
-	[[ "$2" == "--copy" ]] && copy=1
+	# flags
+	flag=$3
+	[[ "$flag" == "--symbolic" ]] && symbolic=1
+	[[ "$flag" == "--copy" ]] && copy=1
 
 	while read file; do
-		fullpath=$destdir/$file
+		fullpath=${source_dir}/$file
 
-		if [[ ! -f $fullpath ]]; then
+		if [[ ! -f "$fullpath" ]]; then
 			echo "File $fullpath does not exist. Skipping it"
 			continue
 		fi
 
 		dir=${file%/*}
-		[[ "$dir" == "$file" ]] && dir=
+		basename=${file##*/}
 
-		mkdir -p "$HOME/$dir"
-		if [[ -n $symbolic ]]; then
-			ln -s "$fullpath" "$HOME/$dir"
-		elif [[ -n $copy ]]; then
-			cp "$fullpath" "$HOME/$dir"
+		if [[ "$file" == "$dir" ]]; then
+			destination="$target_dir/$basename"
+			dir=
 		else
-			ln "$fullpath" "$HOME/$dir"
+			destination="$target_dir/$dir/$basename"
+		fi
+
+		if [[ -f "$destination"  ]]; then
+			echo "Skipping $file because file already exists"
+			continue
+		fi
+
+		mkdir -p "$target_dir/$dir"
+
+		if [[ -n $copy ]]; then
+			cp "$fullpath" "$destination"
+		elif [[ -n $symbolic ]]; then
+			ln -s "$fullpath" "$destination"
+		else
+			ln "$fullpath" "$destination"
 		fi
 
 	done < $DTM_TRACKED_FILES_LIST
@@ -260,13 +247,29 @@ case $action in
 		untrackFiles $@
 		;;
 	link|ln|-L)
-		createLinks $@
+		syncDotFiles $HOME $@
 		;;
 	copy|cp|-c)
-		createLinks "$1" --copy
+		if [[ -n $1 ]]; then
+			dest=$1
+			shift
+		else
+			dest=${DTM_GIT_DIR}
+		fi
+		syncDotFiles $HOME $dest --copy
 		;;
 	sync|-s)
-		syncFrom $@
+		if [[ -n $1 ]]; then
+			dest=$1
+			shift
+			flags=$@
+		else
+			dest=${DTM_GIT_DIR}
+		fi
+		syncDotFiles $dest $HOME $flags
+		;;
+	sync-dirs|-S)
+		syncDotFiles $@
 		;;
 	*)
 		showHelp
